### ISSUE TITLE
Technology Stack Decisions: Visualization

### ISSUE THREAD

**Issue by FWirtz** [openHPI/m.e.i.n.e.l.#1]
Currently, we are deciding between native D3...
# D3 (vanilla)
## Good
- plenty (endless) chart types
- vanilla => expandable

## Bad
- vanilla => complexity 👎 => lots of code for standard charts

---
... and these four frameworks built on top of D3:
# NVD3
## Good
- ~30 chart types

## Bad
- <=IE8 not supported?!

---

# Plotly
## Good
- ~20 chart types
- quickstart guide

## Bad
- documentation not great (good enough though?)

---

# C3
## Good
- ~16 chart types

## Bad
- last update: spring 2016

---

# Vega lite
## Good
- ~20 chart types

## Bad
- all JSON
- no interaction?
- no data updates?
- components?

---
Comment further arguments / frameworks below to add to the discussion. 😊

**Comment by jprberlin** [comment]
I remember we discusses an hybrid approach, so something like plotly + vanilla

**Comment by FWirtz** [comment]
Yes, we also decided on that.
Plotly offers a lot of comfort, but as it makes use of predefined chart types it does not offer the full range of  versatility. Therefore, we will also include some parts of D3. 😊
