### ISSUE TITLE
look deeper into d3.select()

### ISSUE THREAD

**Issue by MaximilianV** [openHPI/m.e.i.n.e.l.#17]
There might be a problem, as d3 seems to search the complete site for the wanted div/id and not the local/shadow dom of the polymer element.
This will cause problems when using multiple components on the same site, using the same div identifiers.

**Comment by Langleu** [comment]
you can get the specific element out of the shadow dom with this.$.myId

**Comment by jak-ing** [comment]
Addressed this in 5257e4a3c01dfa8f2d743bac721024e169a2258e.
A solution is to do a d3.select() on a diagram-wrapping element from the local DOM first before proceeding to select an SVG element (look for diagramDiv in the commit for reference).
