### ISSUE TITLE
Width of demo page not displaying correctly on Mac w/ Firefox

### ISSUE THREAD

**Issue by FWirtz** [openHPI/m.e.i.n.e.l.#25]
The width of the demo page got fixed by adding
```
div.vertical-section-container {
  max-width: 1500px;
}
```
to the CSS. This **doesn't work on Mac w/ Firefox** though (discovered by @jak-ing ).

Look into this and find an appropriate lasting fix.

**Comment by FWirtz** [comment]
Does it work for you guys @MaximilianV @Langleu ?

**Comment by Langleu** [comment]
it's working properly on Ubuntu w/ Firefox.
Is it really necessary if at some point it is responsive and another container around it?

**Comment by jak-ing** [comment]
Works just fine now, weird.
