### ISSUE TITLE
DomStringMap: Data not transmitted correctly if Array of Numbers

### ISSUE THREAD

**Issue by FWirtz** [openHPI/m.e.i.n.e.l.#26]
if data is supplied as array of numbers (see dataset in i.e. activityChart and pieChart), one must insert the following code into the component at the top:
```
<div style="display:none;">{{dataset}}</div>
```
If not, only a `DomStringMap` whill be returned on `this.dataset`.
This only applies to Arrays of Numbers, Arrays of Strings are not included.

**WTF?!**
---
**TODO**: find more elegant way to solve this. Maybe even file a bug with [Polymer](https://github.com/Polymer/polymer).

**Comment by FWirtz** [comment]
@MaximilianV as discussed.

**Comment by FWirtz** [comment]
@jak-ing suggested that it might be due to us using `.ready` instead of `.attached` (changed in branch activity chart afaik), worth looking into
see https://www.polymer-project.org/1.0/docs/devguide/registering-elements#lifecycle-callbacks

**Comment by MaximilianV** [comment]
did anyone tried this solution proposal?

**Comment by MaximilianV** [comment]
tried it in #45 looks good to me for line/bar-chart and datafilter.
Changed piechart in #42 and bubblechart in #44 
Please try it on your own. But I had no further issues after deleting this line.
