### ISSUE TITLE
Create ajax-like component for loading & parsing data and piping it into the diagrams

### ISSUE THREAD

**Issue by FWirtz** [openHPI/m.e.i.n.e.l.#28]
## ToDos
- [x] create component
- [x] document component
- [x] create example of component having a diagram nested inside it that uses the data
- [x] remove ajax part from diagram components

**Comment by MaximilianV** [comment]
Have a look at 9f94d6d
There is an ajax wrapper and the demo works with the bar and line chart :)

**Comment by MaximilianV** [comment]
document component: 369f89b

**Comment by MaximilianV** [comment]
remove ajax part in pie, bar and line (as from linechart-branch): e4548c4

**Comment by FWirtz** [comment]
Fixed by #34
