### ISSUE TITLE
Minimize plotly build

### ISSUE THREAD

**Issue by FWirtz** [openHPI/m.e.i.n.e.l.#31]
https://github.com/plotly/plotly.js/blob/master/dist/README.md#partial-bundles

**Comment by FWirtz** [comment]
also try with vulcanize

**Comment by FWirtz** [comment]
`vulcanize` not working properly, maybe check `npm shrinkwrap`

**Comment by Langleu** [comment]
#33 should fix vulcanize for firefox and also uses polymer-basic
